import { expect, it, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
const state = vi.hoisted(() => ({ user: null as { id: string; role: 'admin' | 'editor' | 'viewer' } | null }));
vi.mock('@/lib/auth', () => ({ auth: async () => state.user }));
vi.mock('@/lib/prisma', async () => {
  const { PrismaClient } = await import('@prisma/client');
  return { prisma: new PrismaClient() };
});
import { prisma } from '@/lib/prisma';
import { POST } from '@/app/api/ai/ask/route';
import { resolveDocumentCapabilities } from '@/lib/document-capability-service';
import { changeDocumentationGrant, removeOrganizationMember } from '@/lib/documentation-grants';
import { administerAccount } from '@/lib/account-administration';
import { decideDocumentReview, submitDocumentReview } from '@/lib/document-review';
import { isImmutableFileReference, LocalImmutableFileStore } from '@/lib/immutable-file-store';
import { publishDocumentReview } from '@/lib/document-publication';
import { readPublishedDocument, readPublishedFile } from '@/lib/published-document-read';
import { readDocumentDetail } from '@/lib/document-detail-read';
import { GET as getDocument } from '@/app/api/documents/[id]/route';
import { discoverDocuments } from '@/lib/document-discovery';
import { GET as getPortalSummary } from '@/app/api/portal/summary/route';
import { buildBackup, ExportIncompleteError } from '@/lib/export';
import { GET as getPublishedAttachment } from '@/app/api/documents/[id]/publications/[snapshotId]/attachments/[attachmentId]/route';
import { readDocumentHistory, createDocumentRevision, restoreDocumentRevision } from '@/lib/document-history';
import { updateDocument } from '@/lib/document-update';
import { changeDocumentLifecycle } from '@/lib/document-lifecycle';
import { discoverDocumentTrash } from '@/lib/document-trash';
import { readDocumentReviews, readReviewedFile } from '@/lib/document-review-read';
import { discoverDocumentReviewers } from '@/lib/document-reviewers';
import { discoverReviewFiles } from '@/lib/document-review-files';
import { listTeamDocumentFiles, readTeamDocumentFile, uploadTeamDocumentFile, deleteTeamDocumentFile } from '@/lib/team-document-files';

it.skipIf(process.env.DOCUMENT_TEST_ISOLATED !== '1' || !process.env.DATABASE_URL)('keeps foreign and private data out of actual provider context', async () => {
  const token = randomUUID();
  const ids: string[] = [];
  const orgs: string[] = [];
  const uploadRoot = mkdtempSync(join(tmpdir(), 'flexdocs-publication-audit-'));
  vi.stubEnv('AI_API_KEY', 'synthetic');
  let context = '';
  const provider = vi.fn(async (_url: unknown, options: RequestInit | undefined) => {
    context = JSON.parse(String(options?.body)).messages[0].content;
    return Response.json({ choices: [{ message: { content: 'Synthetic answer' } }] });
  });
  vi.stubGlobal('fetch', provider);
  try {
    for (const role of ['admin', 'editor', 'viewer'] as const) ids.push((await prisma.user.create({ data: { email: `${token}-${role}@example.invalid`, role } })).id);
    for (const name of ['allowed', 'foreign']) orgs.push((await prisma.organization.create({ data: { name: `${token}-${name}` } })).id);
    for (const userId of ids) await prisma.organizationMember.create({ data: { userId, organizationId: orgs[0] } });
    for (const [index, organizationId] of orgs.entries()) {
      const marker = index ? 'FOREIGN_MARKER' : 'ALLOWED_MARKER';
      await prisma.server.create({ data: { name: marker, userId: ids[0], organizationId } });
      await prisma.flexibleAsset.create({ data: { name: marker, assetType: 'test', userId: ids[0], organizationId } });
      await prisma.document.create({ data: { title: token, content: marker, userId: ids[0], organizationId, visibility: 'org' } });
    }
    await prisma.document.create({ data: { title: token, content: 'PRIVATE_MARKER', userId: ids[0], organizationId: orgs[0], visibility: 'private' } });
    for (const [index, role] of (['admin', 'editor', 'viewer'] as const).entries()) {
      state.user = { id: ids[index], role };
      const response = await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: token, organizationId: orgs[0] }) }));
      expect(response.status).toBe(200);
      expect(context).toContain('ALLOWED_MARKER');
      expect(context).not.toContain('FOREIGN_MARKER');
      if (role !== 'admin') expect(context).not.toContain('PRIVATE_MARKER');
      if (role !== 'admin') {
        await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: token }) }));
        expect(context).not.toContain('FOREIGN_MARKER');
      }
    }
    const teamDocument = { userId: ids[0], ownershipKind: 'organization' as const, organizationId: orgs[0], isArchived: false, deletedAt: null };
    await prisma.organizationDocumentationGrant.create({ data: { userId: ids[1], organizationId: orgs[0], role: 'contributor' } });
    expect((await resolveDocumentCapabilities(teamDocument, { id: ids[1], role: 'editor' })).edit).toBe(true);
    await prisma.organizationMember.deleteMany({ where: { userId: ids[1], organizationId: orgs[0] } });
    expect((await resolveDocumentCapabilities(teamDocument, { id: ids[1], role: 'editor' })).edit).toBe(false);
    await expect(changeDocumentationGrant(ids[2], orgs[0], ids[2], 'reader')).rejects.toMatchObject({ status: 403 });
    await expect(changeDocumentationGrant(ids[0], orgs[0], ids[2], 'contributor')).rejects.toMatchObject({ status: 400 });
    await expect(changeDocumentationGrant(ids[0], orgs[0], ids[1], 'administrator')).rejects.toMatchObject({ status: 400 });
    await changeDocumentationGrant(ids[0], orgs[0], ids[0], 'administrator');
    await expect(changeDocumentationGrant(ids[0], orgs[0], ids[0], null)).rejects.toMatchObject({ status: 409 });
    await prisma.organizationMember.create({ data: { userId: ids[1], organizationId: orgs[0] } });
    await changeDocumentationGrant(ids[0], orgs[0], ids[1], 'administrator');
    const removals = await Promise.allSettled([
      changeDocumentationGrant(ids[0], orgs[0], ids[0], null),
      changeDocumentationGrant(ids[0], orgs[0], ids[1], null),
    ]);
    expect(removals.filter(result => result.status === 'fulfilled')).toHaveLength(1);
    expect(removals.filter(result => result.status === 'rejected')).toHaveLength(1);
    expect(await prisma.organizationDocumentationGrant.count({ where: { organizationId: orgs[0], role: 'administrator' } })).toBe(1);
    expect(await prisma.activityLog.count({ where: { resourceId: orgs[0], action: 'documentation.grant.change' } })).toBe(3);
    const remainingAdmin = await prisma.organizationDocumentationGrant.findFirstOrThrow({ where: { organizationId: orgs[0], role: 'administrator' } });
    await expect(administerAccount(ids[0], remainingAdmin.userId, 'viewer')).rejects.toMatchObject({ status: 409 });
    await expect(administerAccount(ids[0], remainingAdmin.userId, null)).rejects.toMatchObject({ status: remainingAdmin.userId === ids[0] ? 400 : 409 });
    await expect(administerAccount(ids[2], ids[1], 'viewer')).rejects.toMatchObject({ status: 403 });
    await expect(administerAccount(ids[0], ids[0], null)).rejects.toMatchObject({ status: 400 });
    const ownedDocument = await prisma.document.create({ data: { userId: ids[2], title: 'Preserve account-owned Trash', deletedAt: new Date() } });
    await expect(administerAccount(ids[0], ids[2], null)).rejects.toMatchObject({ status: 409 });
    expect(await prisma.document.findUnique({ where: { id: ownedDocument.id } })).not.toBeNull();
    await prisma.document.delete({ where: { id: ownedDocument.id } });
    expect((await administerAccount(ids[0], ids[2], 'editor'))?.role).toBe('editor');
    expect((await administerAccount(ids[0], ids[2], 'viewer'))?.role).toBe('viewer');
    const protectedMember = await prisma.organizationMember.findUniqueOrThrow({ where: { organizationId_userId: { organizationId: orgs[0], userId: remainingAdmin.userId } } });
    await expect(removeOrganizationMember(ids[0], protectedMember.id)).rejects.toMatchObject({ status: 409 });
    await changeDocumentationGrant(ids[0], orgs[0], ids[2], 'reader');
    const readerMembership = await prisma.organizationMember.findUniqueOrThrow({ where: { organizationId_userId: { organizationId: orgs[0], userId: ids[2] } } });
    await expect(removeOrganizationMember(ids[2], readerMembership.id)).rejects.toMatchObject({ status: 403 });
    await removeOrganizationMember(ids[0], readerMembership.id);
    expect(await prisma.organizationDocumentationGrant.count({ where: { userId: ids[2] } })).toBe(0);
    expect(await prisma.activityLog.count({ where: { resourceId: orgs[0], action: 'organization.member.remove' } })).toBe(1);
    await prisma.organizationMember.deleteMany({ where: { userId: ids[2] } });
    state.user = { id: ids[2], role: 'viewer' };
    const callsBefore = provider.mock.calls.length;
    expect((await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: token }) }))).status).toBe(200);
    expect(provider.mock.calls.length).toBe(callsBefore);
    state.user = null;
    expect((await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: '{}' }))).status).toBe(401);
    const draft = await prisma.document.create({ data: { userId: ids[0], title: 'Publication source', content: 'Frozen content', lifecycleState: 'draft' } });
    const revision = await prisma.documentRevision.create({ data: { documentId: draft.id, userId: ids[0], title: draft.title, content: draft.content, category: draft.category, version: 1 } });
    const fileReference = await new LocalImmutableFileStore(uploadRoot).put(Buffer.from([0, 255, 128]));
    const snapshot = await prisma.documentPublication.create({ data: { documentId: draft.id, sourceRevisionId: revision.id, title: draft.title, content: draft.content, category: draft.category, tags: [], attachmentManifest: [{ ...fileReference }], publisherId: ids[0] } });
    const inventory = spawnSync(process.execPath, ['node_modules/tsx/dist/cli.mjs', 'scripts/storage-inventory.ts'], { env: { ...process.env, UPLOAD_DIR: uploadRoot }, encoding: 'utf8' });
    expect([0, 2]).toContain(inventory.status);
    const inventoryReport = JSON.parse(inventory.stdout);
    expect(inventoryReport.invalidPublicationManifests).not.toContain(snapshot.id);
    expect(inventoryReport.unreferenced.some((file: { path: string }) => file.path.endsWith(fileReference.key))).toBe(false);
    expect(inventoryReport.missing).not.toContain(`publication:${snapshot.id}:${fileReference.key}`);
    await expect(prisma.documentPublication.update({ where: { id: snapshot.id }, data: { content: 'Overwrite' } })).rejects.toThrow();
    await expect(prisma.document.update({ where: { id: draft.id }, data: { lifecycleState: 'trashed' } })).rejects.toThrow();
    const other = await prisma.document.findFirstOrThrow({ where: { userId: ids[0], id: { not: draft.id } } });
    await expect(prisma.document.update({ where: { id: other.id }, data: { publishedSnapshotId: snapshot.id } })).rejects.toThrow();
    await expect(prisma.documentPublication.create({ data: { documentId: other.id, sourceRevisionId: revision.id, title: 'Wrong revision', content: '', category: 'general', tags: [], publisherId: ids[0] } })).rejects.toThrow();
    await prisma.document.update({ where: { id: draft.id }, data: { publishedSnapshotId: snapshot.id, lifecycleState: 'published' } });
    await prisma.document.update({ where: { id: draft.id }, data: { content: 'New working content' } });
    expect((await prisma.documentPublication.findUniqueOrThrow({ where: { id: snapshot.id } })).content).toBe('Frozen content');
    await expect(prisma.documentReview.create({ data: { documentId: draft.id, sourceRevisionId: revision.id, submittedById: ids[0], reviewerIds: [], decision: 'approved' } })).rejects.toThrow();
    const reviewDraft = await prisma.document.create({ data: { userId: ids[0], title: 'Review exact version', content: 'Submitted body', lifecycleState: 'draft', tags: { create: { name: 'Frozen review tag', userId: ids[0] } } } });
    const workingPath = join(uploadRoot, 'working-file');
    const originalBytes = Buffer.from([1, 254, 127]);
    writeFileSync(workingPath, originalBytes);
    const workingAttachment = await prisma.attachment.create({ data: { documentId: reviewDraft.id, userId: ids[0], filename: 'review.bin', mimeType: 'application/octet-stream', size: 3, storageType: 'filesystem', filePath: workingPath } });
    const privateUploaderAttachment = await prisma.attachment.create({ data: { documentId: reviewDraft.id, userId: ids[1], filename: 'private.bin', mimeType: 'application/octet-stream', size: 0, storageType: 'base64', data: '' } });
    const storage = new LocalImmutableFileStore(uploadRoot);
    const personalFiles = await discoverReviewFiles(ids[0], reviewDraft.id);
    expect(personalFiles.items.map(file => file.id)).toEqual([workingAttachment.id]);
    expect(personalFiles.items[0]).not.toHaveProperty('filePath');
    expect(personalFiles.items[0]).not.toHaveProperty('data');
    await expect(discoverReviewFiles(ids[1], reviewDraft.id)).rejects.toMatchObject({ status: 404 });
    expect((await discoverDocumentReviewers(ids[0], reviewDraft.id)).items.map(user => user.id)).toEqual([ids[0]]);
    await expect(discoverDocumentReviewers(ids[1], reviewDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(submitDocumentReview(ids[0], reviewDraft.id, reviewDraft.updatedAt.toISOString(), [ids[0]], { attachmentIds: [privateUploaderAttachment.id], uploadRoot, storage })).rejects.toMatchObject({ status: 404 });
    expect(await prisma.documentReview.count({ where: { documentId: reviewDraft.id } })).toBe(0);
    await expect(submitDocumentReview(ids[0], reviewDraft.id, reviewDraft.updatedAt.toISOString(), [ids[2]])).rejects.toMatchObject({ status: 400 });
    const base64ReviewFile = await prisma.attachment.create({ data: { documentId: reviewDraft.id, userId: ids[0], filename: 'empty.bin', mimeType: 'application/octet-stream', size: 0, storageType: 'base64', data: '' } });
    await expect(submitDocumentReview(ids[0], reviewDraft.id, reviewDraft.updatedAt.toISOString(), [ids[0]], { attachmentIds: [base64ReviewFile.id], uploadRoot: join(uploadRoot, 'not-created-yet'),
      storage: { read: reference => storage.read(reference), put: async () => { throw new Error('Synthetic disk failure'); } },
    })).rejects.toMatchObject({ status: 503 });
    expect(await prisma.documentReview.count({ where: { documentId: reviewDraft.id } })).toBe(0);
    expect((await prisma.document.findUniqueOrThrow({ where: { id: reviewDraft.id } })).updatedAt).toEqual(reviewDraft.updatedAt);
    const submitted = await submitDocumentReview(ids[0], reviewDraft.id, reviewDraft.updatedAt.toISOString(), [ids[0]], { attachmentIds: [workingAttachment.id], uploadRoot, storage });
    const reviewList = await readDocumentReviews(ids[0], reviewDraft.id);
    expect(reviewList.items[0]).toMatchObject({ id: submitted.id, canDecide: true, canWithdraw: true, sourceRevision: { content: reviewDraft.content } });
    expect(reviewList.items[0]).not.toHaveProperty('attachmentManifest');
    expect(reviewList.items[0].attachments[0]).not.toHaveProperty('key');
    expect((await readReviewedFile(ids[0], reviewDraft.id, submitted.id, workingAttachment.id, storage)).bytes).toEqual(originalBytes);
    await expect(readReviewedFile(ids[1], reviewDraft.id, submitted.id, workingAttachment.id, storage)).rejects.toMatchObject({ status: 404 });
    await expect(readReviewedFile(ids[0], reviewDraft.id, submitted.id, privateUploaderAttachment.id, storage)).rejects.toMatchObject({ status: 404 });
    await expect(readDocumentReviews(ids[1], reviewDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(decideDocumentReview(ids[0], submitted.id, 'approved', undefined, 'foreign-document')).rejects.toMatchObject({ status: 404 });
    await expect(publishDocumentReview(ids[0], submitted.id, storage, 'foreign-document')).rejects.toMatchObject({ status: 404 });
    expect(submitted.tags).toEqual(['Frozen review tag']);
    const frozenFile = (submitted.attachmentManifest as unknown[])[0];
    expect(isImmutableFileReference(frozenFile)).toBe(true);
    if (!isImmutableFileReference(frozenFile)) throw new Error('Invalid captured reference');
    writeFileSync(workingPath, 'replacement');
    unlinkSync(workingPath);
    expect(await storage.read(frozenFile)).toEqual(originalBytes);
    await expect(prisma.documentReview.update({ where: { id: submitted.id }, data: { tags: ['Replaced tag'] } })).rejects.toThrow();
    await expect(decideDocumentReview(ids[1], submitted.id, 'approved')).rejects.toMatchObject({ status: 404 });
    await prisma.document.update({ where: { id: reviewDraft.id }, data: { content: 'Later working copy', updatedAt: new Date(submitted.submittedAt.getTime() + 1) } });
    await expect(decideDocumentReview(ids[0], submitted.id, 'approved')).rejects.toMatchObject({ status: 409 });
    expect((await prisma.documentReview.findUniqueOrThrow({ where: { id: submitted.id } })).decision).toBe('pending');
    await decideDocumentReview(ids[0], submitted.id, 'withdrawn');
    const freshDraft = await prisma.document.findUniqueOrThrow({ where: { id: reviewDraft.id } });
    const resubmitted = await submitDocumentReview(ids[0], reviewDraft.id, freshDraft.updatedAt.toISOString(), [ids[0]]);
    expect((await decideDocumentReview(ids[0], resubmitted.id, 'approved')).decision).toBe('approved');
    await decideDocumentReview(ids[0], resubmitted.id, 'approved');
    expect(await prisma.activityLog.count({ where: { resourceId: reviewDraft.id, action: 'document.review.approved' } })).toBe(1);
    expect((await prisma.document.findUniqueOrThrow({ where: { id: reviewDraft.id } })).publishedSnapshotId).toBeNull();
    await prisma.document.update({ where: { id: reviewDraft.id }, data: { content: 'Changed after approval' } });
    await expect(publishDocumentReview(ids[0], resubmitted.id, storage)).rejects.toMatchObject({ status: 409 });
    expect(await prisma.documentPublication.count({ where: { documentId: reviewDraft.id } })).toBe(0);
    for (const [index, role] of [[0, 'contributor'], [1, 'reviewer']] as const) {
      await prisma.organizationMember.create({ data: { organizationId: orgs[1], userId: ids[index] } });
      await prisma.organizationDocumentationGrant.create({ data: { organizationId: orgs[1], userId: ids[index], role } });
    }
    const teamDraft = await prisma.document.create({ data: { userId: ids[2], organizationId: orgs[1], ownershipKind: 'organization', lifecycleState: 'draft', title: 'Team review', content: 'Frozen team version' } });
    const teamFile = await prisma.attachment.create({ data: { documentId: teamDraft.id, userId: ids[0], filename: 'legacy.bin', mimeType: 'application/octet-stream', size: originalBytes.length, storageType: 'base64', data: originalBytes.toString('base64') } });
    const teamReview = await submitDocumentReview(ids[0], teamDraft.id, teamDraft.updatedAt.toISOString(), [ids[1]], { attachmentIds: [teamFile.id], uploadRoot, storage });
    expect((await discoverReviewFiles(ids[1], teamDraft.id)).items.map(file => file.id)).toEqual([teamFile.id]);
    expect((await discoverReviewFiles(ids[0], teamDraft.id, 1)).items).toEqual([]);
    const candidates = await discoverDocumentReviewers(ids[0], teamDraft.id);
    expect(candidates.items.map(user => user.id)).toEqual([ids[1]]);
    expect(candidates.total).toBe(1);
    expect(candidates.items[0]).not.toHaveProperty('password');
    expect((await discoverDocumentReviewers(ids[0], teamDraft.id, { page: 1 })).items).toEqual([]);
    expect((await discoverDocumentReviewers(ids[0], teamDraft.id, { query: 'no-match-account-name' })).total).toBe(0);
    await expect(discoverDocumentReviewers(ids[2], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await prisma.attachment.delete({ where: { id: teamFile.id } });
    const teamFrozenFile = (teamReview.attachmentManifest as unknown[])[0];
    if (!isImmutableFileReference(teamFrozenFile)) throw new Error('Invalid captured team file');
    expect(await storage.read(teamFrozenFile)).toEqual(originalBytes);
    expect((await readReviewedFile(ids[0], teamDraft.id, teamReview.id, teamFile.id, storage)).bytes).toEqual(originalBytes);
    await expect(readReviewedFile(ids[1], teamDraft.id, teamReview.id, teamFile.id, {
      put: bytes => storage.put(bytes), read: async reference => {
        const bytes = await storage.read(reference);
        await prisma.organizationMember.deleteMany({ where: { organizationId: orgs[1], userId: ids[1] } });
        return bytes;
      },
    })).rejects.toMatchObject({ status: 404 });
    await expect(decideDocumentReview(ids[0], teamReview.id, 'approved')).rejects.toMatchObject({ status: 404 });
    await prisma.organizationMember.deleteMany({ where: { organizationId: orgs[1], userId: ids[1] } });
    await expect(decideDocumentReview(ids[1], teamReview.id, 'approved')).rejects.toMatchObject({ status: 404 });
    expect((await discoverDocumentReviewers(ids[0], teamDraft.id)).total).toBe(0);
    await expect(discoverReviewFiles(ids[1], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await prisma.organizationMember.create({ data: { organizationId: orgs[1], userId: ids[1] } });
    expect((await decideDocumentReview(ids[1], teamReview.id, 'approved')).decision).toBe('approved');
    await expect(publishDocumentReview(ids[0], teamReview.id, storage)).rejects.toMatchObject({ status: 404 });
    const objectPath = join(uploadRoot, 'publication-objects', teamFrozenFile.key);
    writeFileSync(objectPath, 'corrupted');
    await expect(publishDocumentReview(ids[1], teamReview.id, storage)).rejects.toMatchObject({ status: 409 });
    expect(await prisma.documentPublication.count({ where: { documentId: teamDraft.id } })).toBe(0);
    expect((await prisma.document.findUniqueOrThrow({ where: { id: teamDraft.id } })).publishedSnapshotId).toBeNull();
    writeFileSync(objectPath, originalBytes);
    const published = await Promise.all([publishDocumentReview(ids[1], teamReview.id, storage), publishDocumentReview(ids[1], teamReview.id, storage)]);
    expect(published.filter(result => !result.replayed)).toHaveLength(1);
    expect(new Set(published.map(result => result.snapshot.id)).size).toBe(1);
    expect(await prisma.activityLog.count({ where: { resourceId: teamDraft.id, action: 'document.publish' } })).toBe(1);
    expect(published[0].snapshot.content).toBe('Frozen team version');
    expect(published[0].snapshot.attachmentManifest).toEqual(teamReview.attachmentManifest);
    await prisma.document.update({ where: { id: teamDraft.id }, data: { title: 'Working team title', content: 'New unpublished working body', lifecycleState: 'draft' } });
    const replayedPublication = await publishDocumentReview(ids[1], teamReview.id, storage);
    expect(replayedPublication.replayed).toBe(true);
    expect(replayedPublication.snapshot.content).toBe('Frozen team version');
    expect((await prisma.document.findUniqueOrThrow({ where: { id: teamDraft.id } })).content).toBe('New unpublished working body');
    await expect(readPublishedDocument(ids[2], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(readDocumentDetail(ids[2], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    expect(await readDocumentDetail(ids[0], teamDraft.id)).toMatchObject({ content: 'New unpublished working body', representation: 'working', canEdit: true, canManageLifecycle: false });
    await prisma.organizationMember.create({ data: { userId: ids[2], organizationId: orgs[1] } });
    await prisma.organizationDocumentationGrant.create({ data: { userId: ids[2], organizationId: orgs[1], role: 'reader' } });
    const readerView = await readPublishedDocument(ids[2], teamDraft.id);
    vi.stubEnv('UPLOAD_DIR', uploadRoot);
    const fileParams = { params: Promise.resolve({ id: teamDraft.id, snapshotId: readerView.snapshotId, attachmentId: teamFile.id }) };
    state.user = { id: ids[2], role: 'viewer' };
    const publishedDownload = await getPublishedAttachment(new Request('http://localhost'), fileParams);
    expect(publishedDownload.status).toBe(200);
    expect(Buffer.from(await publishedDownload.arrayBuffer())).toEqual(originalBytes);
    expect(publishedDownload.headers.get('Cache-Control')).toBe('private, no-store');
    state.user = null;
    expect((await getPublishedAttachment(new Request('http://localhost'), fileParams)).status).toBe(401);
    await expect(buildBackup({ organizationId: orgs[1] })).rejects.toBeInstanceOf(ExportIncompleteError);
    state.user = { id: ids[2], role: 'viewer' };
    expect((await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: 'Frozen team version', organizationId: orgs[1] }) }))).status).toBe(200);
    expect(context).toContain('Frozen team version');
    expect(context).not.toContain('New unpublished working body');
    expect(context).not.toContain('Working team title');
    state.user = { id: ids[0], role: 'admin' };
    await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: 'New unpublished working body', organizationId: orgs[1] }) }));
    expect(context).toContain('New unpublished working body');
    for (const [index, role] of [[2, 'viewer'], [0, 'admin']] as const) {
      state.user = { id: ids[index], role };
      const portal = await getPortalSummary();
      expect(portal.status).toBe(200);
      const kb = (await portal.json()).kb;
      expect(kb.find((item: { id: string }) => item.id === teamDraft.id)).toMatchObject({ title: 'Team review' });
      expect(JSON.stringify(kb)).not.toContain('Working team title');
    }
    const discovered = await discoverDocuments(ids[2], { query: 'Frozen team version', page: 0, limit: 1 });
    expect(discovered.total).toBe(1);
    expect(discovered.items[0]).toMatchObject({ id: teamDraft.id, content: 'Frozen team version', representation: 'published' });
    expect(discovered.items[0]).not.toHaveProperty('publishedSnapshot');
    expect(discovered.items[0]).not.toHaveProperty('userId');
    expect((await discoverDocuments(ids[2], { query: 'New unpublished working body', page: 0, limit: 10 })).total).toBe(0);
    expect((await discoverDocuments(ids[2], { query: 'Frozen team version', page: 1, limit: 1 })).items).toEqual([]);
    expect((await discoverDocuments(ids[0], { query: 'New unpublished working body', page: 0, limit: 10 })).items[0]).toMatchObject({ id: teamDraft.id, representation: 'working' });
    expect((await discoverDocuments(ids[2], { query: 'Frozen team version', organizationId: orgs[0], page: 0, limit: 10 })).total).toBe(0);
    const olderTeam = await prisma.document.create({ data: { userId: ids[0], organizationId: orgs[1], ownershipKind: 'organization', lifecycleState: 'draft', title: 'Working title only', content: 'Unpublished older body', category: 'working-category', isPinned: true } });
    const olderRevision = await prisma.documentRevision.create({ data: { documentId: olderTeam.id, userId: ids[0], version: 1, title: 'Older publication', content: 'Frozen team version alternate', category: 'frozen-category' } });
    const olderSnapshot = await prisma.documentPublication.create({ data: { documentId: olderTeam.id, sourceRevisionId: olderRevision.id, title: olderRevision.title, content: olderRevision.content, category: olderRevision.category, tags: [], publisherId: ids[1], publishedAt: new Date('2000-01-01T00:00:00Z') } });
    await prisma.document.update({ where: { id: olderTeam.id }, data: { publishedSnapshotId: olderSnapshot.id } });
    const sortedPublications = await discoverDocuments(ids[2], { query: 'Frozen team version', page: 0, limit: 1 });
    expect(sortedPublications.total).toBe(2);
    expect(sortedPublications.hasMore).toBe(true);
    expect(sortedPublications.items[0].id).toBe(teamDraft.id);
    const olderPage = await discoverDocuments(ids[2], { query: 'Frozen team version', page: 1, limit: 1 });
    expect(olderPage.items[0]).toMatchObject({ id: olderTeam.id, title: 'Older publication', category: 'frozen-category', isPinned: false, updatedAt: olderSnapshot.publishedAt });
    expect((await discoverDocuments(ids[2], { category: 'working-category', page: 0, limit: 10 })).total).toBe(0);
    expect((await discoverDocuments(ids[2], { category: 'frozen-category', page: 0, limit: 10 })).total).toBe(1);
    state.user = { id: ids[2], role: 'viewer' };
    const detailResponse = await getDocument(new Request('http://localhost/api/documents/' + teamDraft.id), { params: Promise.resolve({ id: teamDraft.id }) });
    expect(detailResponse.status).toBe(200);
    const detail = await detailResponse.json();
    expect(detail).toMatchObject({ content: 'Frozen team version', representation: 'published', canEdit: false, folder: null });
    expect(detail).not.toHaveProperty('publishedSnapshot');
    expect(detail).not.toHaveProperty('userId');
    expect(detail.attachments[0]).not.toHaveProperty('key');
    state.user = null;
    expect((await getDocument(new Request('http://localhost/api/documents/' + teamDraft.id), { params: Promise.resolve({ id: teamDraft.id }) })).status).toBe(401);
    expect(readerView.content).toBe('Frozen team version');
    expect(readerView.attachments).toEqual([{ attachmentId: teamFile.id, filename: 'legacy.bin', mimeType: 'application/octet-stream', size: originalBytes.length }]);
    expect(readerView).not.toHaveProperty('sourceRevisionId');
    expect(readerView.attachments[0]).not.toHaveProperty('key');
    expect(readerView.attachments[0]).not.toHaveProperty('sha256');
    expect((await readPublishedFile(ids[2], teamDraft.id, readerView.snapshotId, teamFile.id, storage)).bytes).toEqual(originalBytes);
    await expect(readPublishedFile(ids[2], teamDraft.id, 'foreign-snapshot', teamFile.id, storage)).rejects.toMatchObject({ status: 404 });
    await expect(readPublishedFile(ids[2], teamDraft.id, readerView.snapshotId, 'unselected-file', storage)).rejects.toMatchObject({ status: 404 });
    await prisma.organizationDocumentationGrant.deleteMany({ where: { userId: ids[0], organizationId: orgs[1] } });
    await expect(readPublishedDocument(ids[0], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(readDocumentDetail(ids[0], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    expect((await discoverDocuments(ids[0], { query: 'New unpublished working body', page: 0, limit: 10 })).total).toBe(0);
    state.user = { id: ids[0], role: 'admin' };
    expect((await (await getPortalSummary()).json()).kb.some((item: { id: string }) => item.id === teamDraft.id)).toBe(false);
    await prisma.organizationDocumentationGrant.create({ data: { userId: ids[0], organizationId: orgs[1], role: 'contributor' } });
    const revokingStorage = { put: storage.put.bind(storage), read: async (reference: Parameters<typeof storage.read>[0]) => {
      const bytes = await storage.read(reference);
      await prisma.organizationMember.deleteMany({ where: { userId: ids[2], organizationId: orgs[1] } });
      return bytes;
    } };
    await expect(readPublishedFile(ids[2], teamDraft.id, readerView.snapshotId, teamFile.id, revokingStorage)).rejects.toMatchObject({ status: 404 });
    await expect(readPublishedDocument(ids[2], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await prisma.organizationMember.create({ data: { userId: ids[2], organizationId: orgs[1] } });
    writeFileSync(objectPath, 'corrupted');
    await expect(readPublishedFile(ids[2], teamDraft.id, readerView.snapshotId, teamFile.id, storage)).rejects.toMatchObject({ status: 503 });
    writeFileSync(objectPath, originalBytes);
    await prisma.organizationMember.deleteMany({ where: { userId: ids[1], organizationId: orgs[1] } });
    await expect(publishDocumentReview(ids[1], teamReview.id, storage)).rejects.toMatchObject({ status: 404 });
    expect((await readPublishedDocument(ids[2], teamDraft.id)).content).toBe('Frozen team version');
    await prisma.organizationMember.create({ data: { userId: ids[1], organizationId: orgs[1] } });
    await prisma.document.update({ where: { id: teamDraft.id }, data: { lifecycleState: 'archived', isArchived: true } });
    await expect(publishDocumentReview(ids[1], teamReview.id, storage)).rejects.toMatchObject({ status: 404 });
    await expect(readPublishedDocument(ids[2], teamDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(readPublishedFile(ids[2], teamDraft.id, readerView.snapshotId, teamFile.id, storage)).rejects.toMatchObject({ status: 404 });
    const privateDraft = await prisma.document.findUniqueOrThrow({ where: { id: reviewDraft.id } });
    const privateReview = await submitDocumentReview(ids[0], privateDraft.id, privateDraft.updatedAt.toISOString(), [ids[0]]);
    await decideDocumentReview(ids[0], privateReview.id, 'approved');
    await publishDocumentReview(ids[0], privateReview.id, storage);
    expect((await readPublishedDocument(ids[0], privateDraft.id)).content).toBe('Changed after approval');
    await expect(readPublishedDocument(ids[2], privateDraft.id)).rejects.toMatchObject({ status: 404 });
    await prisma.document.update({ where: { id: privateDraft.id }, data: { organizationId: orgs[1], visibility: 'org', content: 'Unpublished personal edits', lifecycleState: 'draft' } });
    expect((await readPublishedDocument(ids[2], privateDraft.id)).content).toBe('Changed after approval');
    expect(await readDocumentDetail(ids[2], privateDraft.id)).toMatchObject({ content: 'Changed after approval', representation: 'published', canEdit: false });
    expect((await discoverDocuments(ids[2], { query: 'Changed after approval', page: 0, limit: 10 })).items.some(item => item.id === privateDraft.id && item.representation === 'published')).toBe(true);
    expect((await discoverDocuments(ids[2], { query: 'Unpublished personal edits', page: 0, limit: 10 })).total).toBe(0);
    expect(await readDocumentDetail(ids[0], privateDraft.id)).toMatchObject({ content: 'Unpublished personal edits', representation: 'working', canEdit: true });
    state.user = { id: ids[2], role: 'viewer' };
    await POST(new Request('http://localhost/api/ai/ask', { method: 'POST', body: JSON.stringify({ question: 'Changed after approval', organizationId: orgs[1] }) }));
    expect(context).toContain('Changed after approval');
    expect(context).not.toContain('Unpublished personal edits');
    await prisma.document.update({ where: { id: privateDraft.id }, data: { visibility: 'private' } });
    await expect(readPublishedDocument(ids[2], privateDraft.id)).rejects.toMatchObject({ status: 404 });
    await expect(readDocumentDetail(ids[2], privateDraft.id)).rejects.toMatchObject({ status: 404 });
    expect((await discoverDocuments(ids[2], { query: 'Changed after approval', page: 0, limit: 10 })).items.some(item => item.id === privateDraft.id)).toBe(false);
    const fileDocument = await prisma.document.create({ data: { userId: ids[2], organizationId: orgs[1], ownershipKind: 'organization', lifecycleState: 'draft', title: 'Team working files' } });
    await expect(uploadTeamDocumentFile(ids[0], fileDocument.id, undefined, { bytes: originalBytes, filename: 'team.bin', mimeType: 'application/octet-stream' }, { uploadRoot })).rejects.toMatchObject({ status: 428 });
    await expect(uploadTeamDocumentFile(ids[2], fileDocument.id, fileDocument.updatedAt.toISOString(), { bytes: originalBytes, filename: 'denied.bin', mimeType: 'application/octet-stream' }, { uploadRoot })).rejects.toMatchObject({ status: 404 });
    const fileAttempts = await Promise.allSettled([0, 1].map(() => uploadTeamDocumentFile(ids[0], fileDocument.id, fileDocument.updatedAt.toISOString(), { bytes: originalBytes, filename: 'team.bin', mimeType: 'application/octet-stream' }, { uploadRoot })));
    expect(fileAttempts.filter(result => result.status === 'fulfilled')).toHaveLength(1);
    expect(fileAttempts.filter(result => result.status === 'rejected').map(result => result.status === 'rejected' && result.reason.status)).toEqual([409]);
    const teamWorking = (await listTeamDocumentFiles(ids[1], fileDocument.id)).items[0];
    expect(teamWorking).not.toHaveProperty('filePath'); expect(teamWorking).not.toHaveProperty('data');
    expect((await listTeamDocumentFiles(ids[1], fileDocument.id, 1)).items).toEqual([]);
    await expect(listTeamDocumentFiles(ids[2], fileDocument.id)).rejects.toMatchObject({ status: 404 });
    expect((await readTeamDocumentFile(ids[1], fileDocument.id, teamWorking.id, { uploadRoot })).bytes).toEqual(originalBytes);
    await expect(readTeamDocumentFile(ids[1], teamDraft.id, teamWorking.id, { uploadRoot })).rejects.toMatchObject({ status: 404 });
    const fileVersion = (await prisma.document.findUniqueOrThrow({ where: { id: fileDocument.id } })).updatedAt.toISOString();
    await expect(uploadTeamDocumentFile(ids[0], fileDocument.id, fileVersion, { bytes: originalBytes, filename: 'failed.bin', mimeType: 'application/octet-stream' }, { uploadRoot,
      storage: { read: reference => storage.read(reference), put: async () => { throw new Error('Synthetic storage failure'); } },
    })).rejects.toMatchObject({ status: 503 });
    expect((await prisma.document.findUniqueOrThrow({ where: { id: fileDocument.id } })).updatedAt.toISOString()).toBe(fileVersion);
    expect(await prisma.attachment.count({ where: { documentId: fileDocument.id } })).toBe(1);
    const fileReview = await submitDocumentReview(ids[0], fileDocument.id, fileVersion, [ids[1]], { attachmentIds: [teamWorking.id], uploadRoot, storage });
    const changedFile = await uploadTeamDocumentFile(ids[1], fileDocument.id, fileReview.submittedAt.toISOString(), { bytes: Buffer.from('new'), filename: 'new.bin', mimeType: 'application/octet-stream' }, { uploadRoot });
    expect((await prisma.documentReview.findUniqueOrThrow({ where: { id: fileReview.id } })).decision).toBe('withdrawn');
    expect((await readReviewedFile(ids[0], fileDocument.id, fileReview.id, teamWorking.id, storage)).bytes).toEqual(originalBytes);
    await expect(deleteTeamDocumentFile(ids[1], fileDocument.id, teamWorking.id, changedFile.updatedAt.toISOString(), { uploadRoot,
      storage: { read: reference => storage.read(reference), put: async () => { throw new Error('Synthetic retention failure'); } },
    })).rejects.toMatchObject({ status: 503 });
    expect(await prisma.attachment.findUnique({ where: { id: teamWorking.id } })).not.toBeNull();
    expect((await prisma.document.findUniqueOrThrow({ where: { id: fileDocument.id } })).updatedAt).toEqual(changedFile.updatedAt);
    await deleteTeamDocumentFile(ids[1], fileDocument.id, teamWorking.id, changedFile.updatedAt.toISOString());
    await expect(readTeamDocumentFile(ids[0], fileDocument.id, teamWorking.id, { uploadRoot })).rejects.toMatchObject({ status: 404 });
    expect((await readReviewedFile(ids[0], fileDocument.id, fileReview.id, teamWorking.id, storage)).bytes).toEqual(originalBytes);
    await expect(readTeamDocumentFile(ids[1], fileDocument.id, changedFile.attachment.id, { uploadRoot, readBytes: async attachment => {
      await prisma.organizationMember.delete({ where: { organizationId_userId: { organizationId: orgs[1], userId: ids[1] } } });
      return Buffer.from('new');
    } })).rejects.toMatchObject({ status: 404 });
    await prisma.organizationMember.create({ data: { userId: ids[1], organizationId: orgs[1] } });
    const historyDocument = await prisma.document.create({ data: { userId: ids[2], organizationId: orgs[1], ownershipKind: 'organization', lifecycleState: 'draft', title: 'Current team working history', content: 'Current internal working content' } });
    const archivedFiles = await prisma.document.update({ where: { id: fileDocument.id }, data: { isArchived: true, lifecycleState: 'archived' } });
    expect((await listTeamDocumentFiles(ids[1], fileDocument.id)).items).toHaveLength(1);
    expect((await readTeamDocumentFile(ids[1], fileDocument.id, changedFile.attachment.id, { uploadRoot })).bytes).toEqual(Buffer.from('new'));
    await expect(listTeamDocumentFiles(ids[2], fileDocument.id)).rejects.toMatchObject({ status: 404 });
    await expect(deleteTeamDocumentFile(ids[1], fileDocument.id, changedFile.attachment.id, archivedFiles.updatedAt.toISOString())).rejects.toMatchObject({ status: 404 });
    const oldInternal = await prisma.documentRevision.create({ data: { documentId: historyDocument.id, userId: ids[1], version: 1, title: 'Old internal title', content: 'Old internal history content', category: 'general' } });
    const publishedRevision = await prisma.documentRevision.create({ data: { documentId: historyDocument.id, userId: ids[1], version: 2, title: 'History publication', content: 'Frozen history reader content', category: 'general' } });
    const historyPublication = await prisma.documentPublication.create({ data: { documentId: historyDocument.id, sourceRevisionId: publishedRevision.id, publisherId: ids[1], title: publishedRevision.title, content: publishedRevision.content, category: 'general', tags: [] } });
    await prisma.document.update({ where: { id: historyDocument.id }, data: { publishedSnapshotId: historyPublication.id, lifecycleState: 'published' } });
    await expect(readDocumentHistory(ids[2], historyDocument.id)).rejects.toMatchObject({ status: 404 });
    expect((await readDocumentHistory(ids[0], historyDocument.id)).map(revision => revision.id)).toEqual([publishedRevision.id, oldInternal.id]);
    await expect(createDocumentRevision(ids[0], historyDocument.id, { content: 'New internal content' })).rejects.toMatchObject({ status: 428 });
    const historyVersion = (await prisma.document.findUniqueOrThrow({ where: { id: historyDocument.id } })).updatedAt.toISOString();
    const historyAttempts = await Promise.allSettled([0, 1].map(() => createDocumentRevision(ids[0], historyDocument.id, { content: 'New internal content', expectedUpdatedAt: historyVersion })));
    expect(historyAttempts.filter(result => result.status === 'fulfilled')).toHaveLength(1);
    expect(historyAttempts.filter(result => result.status === 'rejected').map(result => result.status === 'rejected' && result.reason.status)).toEqual([409]);
    expect(await prisma.activityLog.count({ where: { resourceId: historyDocument.id, action: 'document.revision.create' } })).toBe(1);
    const beforeReview = await prisma.document.findUniqueOrThrow({ where: { id: historyDocument.id } });
    const supersededReview = await submitDocumentReview(ids[0], historyDocument.id, beforeReview.updatedAt.toISOString(), [ids[1]]);
    const restoredHistory = await restoreDocumentRevision(ids[0], historyDocument.id, oldInternal.id, supersededReview.submittedAt.toISOString());
    expect(restoredHistory).toMatchObject({ userId: ids[0], content: 'Old internal history content' });
    expect((await prisma.document.findUniqueOrThrow({ where: { id: historyDocument.id } }))).toMatchObject({ lifecycleState: 'draft', publishedSnapshotId: historyPublication.id });
    expect((await readPublishedDocument(ids[2], historyDocument.id)).content).toBe('Frozen history reader content');
    expect((await prisma.documentReview.findUniqueOrThrow({ where: { id: supersededReview.id } })).decision).toBe('withdrawn');
    expect(await prisma.activityLog.count({ where: { resourceId: historyDocument.id, action: 'document.history.restore' } })).toBe(1);
    await expect(restoreDocumentRevision(ids[0], historyDocument.id, oldInternal.id, historyVersion)).rejects.toMatchObject({ status: 409 });
    await expect(restoreDocumentRevision(ids[0], historyDocument.id, oldInternal.id)).rejects.toMatchObject({ status: 428 });
    await expect(restoreDocumentRevision(ids[0], historyDocument.id, publishedRevision.id + '-foreign', restoredHistory.updatedAt.toISOString())).rejects.toMatchObject({ status: 404 });
    await expect(restoreDocumentRevision(ids[0], historyDocument.id, submitted.sourceRevisionId, restoredHistory.updatedAt.toISOString())).rejects.toMatchObject({ status: 404 });
    await prisma.organizationDocumentationGrant.deleteMany({ where: { userId: ids[0], organizationId: orgs[1] } });
    await expect(readDocumentHistory(ids[0], historyDocument.id)).rejects.toMatchObject({ status: 404 });
    await expect(restoreDocumentRevision(ids[0], historyDocument.id, oldInternal.id, restoredHistory.updatedAt.toISOString())).rejects.toMatchObject({ status: 404 });
    await expect(updateDocument(ids[0], historyDocument.id, { content: 'Denied edit', expectedUpdatedAt: restoredHistory.updatedAt.toISOString() })).rejects.toMatchObject({ status: 404 });
    await prisma.organizationDocumentationGrant.create({ data: { userId: ids[0], organizationId: orgs[1], role: 'contributor' } });
    const teamFolder = await prisma.folder.create({ data: { name: token, userId: ids[1], organizationId: orgs[1], ownershipKind: 'organization' } });
    const foreignFolder = await prisma.folder.create({ data: { name: token + '-foreign', userId: ids[0], organizationId: orgs[0], ownershipKind: 'organization' } });
    const personalFolder = await prisma.folder.create({ data: { name: token + '-personal', userId: ids[0], organizationId: orgs[1] } });
    for (const folderId of [foreignFolder.id, personalFolder.id]) await expect(updateDocument(ids[0], historyDocument.id, { folderId, expectedUpdatedAt: restoredHistory.updatedAt.toISOString() })).rejects.toMatchObject({ status: 404 });
    await expect(updateDocument(ids[0], historyDocument.id, { content: 'Blind edit' })).rejects.toMatchObject({ status: 428 });
    await expect(updateDocument(ids[0], historyDocument.id, { visibility: 'org', expectedUpdatedAt: restoredHistory.updatedAt.toISOString() })).rejects.toMatchObject({ status: 400 });
    await expect(updateDocument(ids[0], historyDocument.id, { isArchived: true, expectedUpdatedAt: restoredHistory.updatedAt.toISOString() })).rejects.toMatchObject({ status: 409 });
    const updateReview = await submitDocumentReview(ids[0], historyDocument.id, restoredHistory.updatedAt.toISOString(), [ids[1]]);
    const updatedTeam = await updateDocument(ids[0], historyDocument.id, { content: 'Team working edit after review', tags: [token], folderId: teamFolder.id, expectedUpdatedAt: updateReview.submittedAt.toISOString() });
    expect(updatedTeam).toMatchObject({ content: 'Team working edit after review', lifecycleState: 'draft', publishedSnapshotId: historyPublication.id, canEdit: true, canManageLifecycle: false, folderId: teamFolder.id });
    expect(updatedTeam.tags.map(tag => tag.name)).toEqual([token]);
    expect((await prisma.documentReview.findUniqueOrThrow({ where: { id: updateReview.id } })).decision).toBe('withdrawn');
    expect((await readPublishedDocument(ids[2], historyDocument.id)).content).toBe('Frozen history reader content');
    const editAttempts = await Promise.allSettled([0, 1].map(() => updateDocument(ids[0], historyDocument.id, { isPinned: true, expectedUpdatedAt: updatedTeam.updatedAt.toISOString() })));
    expect(editAttempts.filter(result => result.status === 'fulfilled')).toHaveLength(1);
    expect(editAttempts.filter(result => result.status === 'rejected').map(result => result.status === 'rejected' && result.reason.status)).toEqual([409]);
    expect(await prisma.activityLog.count({ where: { resourceId: historyDocument.id, action: 'document.update' } })).toBe(2);
    const lifecycleVersion = (await prisma.document.findUniqueOrThrow({ where: { id: historyDocument.id } })).updatedAt.toISOString();
    await expect(changeDocumentLifecycle(ids[0], historyDocument.id, 'archive', lifecycleVersion)).rejects.toMatchObject({ status: 404 });
    await prisma.organizationDocumentationGrant.update({ where: { organizationId_userId: { organizationId: orgs[1], userId: ids[0] } }, data: { role: 'administrator' } });
    await expect(changeDocumentLifecycle(ids[0], historyDocument.id, 'archive')).rejects.toMatchObject({ status: 428 });
    expect(await readDocumentDetail(ids[0], historyDocument.id)).toMatchObject({ canManageLifecycle: true, canEdit: true });
    const archivedTeam = await changeDocumentLifecycle(ids[0], historyDocument.id, 'archive', lifecycleVersion);
    expect(await readDocumentDetail(ids[0], historyDocument.id)).toMatchObject({ canManageLifecycle: true, canEdit: false, isArchived: true });
    expect(archivedTeam.document).toMatchObject({ lifecycleState: 'archived', isArchived: true, publishedSnapshotId: historyPublication.id });
    await expect(readPublishedDocument(ids[2], historyDocument.id)).rejects.toMatchObject({ status: 404 });
    expect((await discoverDocuments(ids[2], { query: 'Frozen history reader content', page: 0, limit: 10 })).total).toBe(0);
    await expect(updateDocument(ids[0], historyDocument.id, { content: 'Denied archived edit', expectedUpdatedAt: archivedTeam.document.updatedAt.toISOString() })).rejects.toMatchObject({ status: 404 });
    await expect(changeDocumentLifecycle(ids[0], historyDocument.id, 'unarchive', lifecycleVersion)).rejects.toMatchObject({ status: 409 });
    const trashedArchive = await changeDocumentLifecycle(ids[0], historyDocument.id, 'trash', archivedTeam.document.updatedAt.toISOString());
    expect(trashedArchive.document).toMatchObject({ lifecycleState: 'trashed', isArchived: true });
    const trashOptions = { query: trashedArchive.document.title, organizationId: orgs[1], page: 0, limit: 1 };
    const teamTrashList = await discoverDocumentTrash(ids[0], trashOptions);
    expect(teamTrashList.items).toEqual([expect.objectContaining({ id: historyDocument.id, canRestore: true })]);
    expect(teamTrashList.items[0]).not.toHaveProperty('content');
    expect(teamTrashList.total).toBe(1);
    expect((await discoverDocumentTrash(ids[1], trashOptions)).total).toBe(0);
    expect((await discoverDocumentTrash(ids[2], trashOptions)).total).toBe(0);
    expect((await discoverDocumentTrash(ids[0], { ...trashOptions, organizationId: orgs[0] })).total).toBe(0);
    await prisma.organizationDocumentationGrant.update({ where: { organizationId_userId: { organizationId: orgs[1], userId: ids[0] } }, data: { role: 'contributor' } });
    expect((await discoverDocumentTrash(ids[0], trashOptions)).total).toBe(0);
    await prisma.organizationDocumentationGrant.update({ where: { organizationId_userId: { organizationId: orgs[1], userId: ids[0] } }, data: { role: 'administrator' } });
    const recoveredArchive = await changeDocumentLifecycle(ids[0], historyDocument.id, 'restore', trashedArchive.document.updatedAt.toISOString());
    expect(recoveredArchive.document).toMatchObject({ lifecycleState: 'archived', isArchived: true, publishedSnapshotId: null, deletedAt: null });
    const unarchived = await changeDocumentLifecycle(ids[0], historyDocument.id, 'unarchive', recoveredArchive.document.updatedAt.toISOString());
    expect(unarchived.document).toMatchObject({ lifecycleState: 'draft', isArchived: false, publishedSnapshotId: null });
    expect(await prisma.documentPublication.count({ where: { id: historyPublication.id } })).toBe(1);
    await expect(readPublishedDocument(ids[2], historyDocument.id)).rejects.toMatchObject({ status: 404 });
    const trashRace = await Promise.allSettled([0, 1].map(() => changeDocumentLifecycle(ids[0], historyDocument.id, 'trash', unarchived.document.updatedAt.toISOString())));
    expect(trashRace.filter(result => result.status === 'fulfilled')).toHaveLength(1);
    expect(trashRace.filter(result => result.status === 'rejected').map(result => result.status === 'rejected' && result.reason.status)).toEqual([409]);
    expect(await prisma.activityLog.count({ where: { resourceId: historyDocument.id, action: 'document.lifecycle.trash' } })).toBe(2);
    const reviewInventory = spawnSync(process.execPath, ['node_modules/tsx/dist/cli.mjs', 'scripts/storage-inventory.ts'], { env: { ...process.env, UPLOAD_DIR: uploadRoot }, encoding: 'utf8' });
    expect([0, 2]).toContain(reviewInventory.status);
    const reviewInventoryReport = JSON.parse(reviewInventory.stdout);
    expect(reviewInventoryReport.invalidReviewManifests).not.toContain(submitted.id);
    expect(reviewInventoryReport.unreferenced.some((file: { path: string }) => file.path.endsWith(frozenFile.key))).toBe(false);
    expect(reviewInventoryReport.missing).not.toContain(`review:${submitted.id}:${frozenFile.key}`);
  } finally {
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
    await prisma.document.updateMany({ where: { userId: { in: ids } }, data: { publishedSnapshotId: null } });
    await prisma.documentPublication.deleteMany({ where: { publisherId: { in: ids } } });
    await prisma.documentReview.deleteMany({ where: { submittedById: { in: ids } } });
    await prisma.attachment.deleteMany({ where: { userId: { in: ids } } });
    await prisma.document.deleteMany({ where: { userId: { in: ids } } });
    await prisma.folder.deleteMany({ where: { userId: { in: ids } } });
    await prisma.tag.deleteMany({ where: { userId: { in: ids } } });
    await prisma.server.deleteMany({ where: { userId: { in: ids } } });
    await prisma.flexibleAsset.deleteMany({ where: { userId: { in: ids } } });
    await prisma.organizationMember.deleteMany({ where: { userId: { in: ids } } });
    await prisma.organizationDocumentationGrant.deleteMany({ where: { userId: { in: ids } } });
    await prisma.activityLog.deleteMany({ where: { userId: { in: ids } } });
    await prisma.organization.deleteMany({ where: { id: { in: orgs } } });
    await prisma.user.deleteMany({ where: { id: { in: ids } } });
    await prisma.$disconnect();
    rmSync(uploadRoot, { recursive: true });
  }
}, 30_000);
