import { expect, it, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import { spawnSync } from 'node:child_process';
vi.mock('@/lib/prisma', async () => {
  const { PrismaClient } = await import('@prisma/client');
  return { prisma: new PrismaClient() };
});
import { prisma } from '@/lib/prisma';
import { previewDocumentOwnership } from '@/lib/document-ownership-preview';
import { prepareDocumentOwnershipRequest, readDocumentOwnershipRequest, cancelDocumentOwnershipRequest } from '@/lib/document-ownership-requests';
import { changeDocumentationGrant } from '@/lib/documentation-grants';
import { deleteOrganization } from '@/lib/organization-administration';

it.skipIf(process.env.DOCUMENT_TEST_ISOLATED !== '1' || !process.env.DATABASE_URL)('persists immutable keyed ownership requests without converting documents', async () => {
  const token = randomUUID();
  const ids: string[] = [];
  let organizationId: string | undefined;
  let documentId: string | undefined;
  let associatedDocumentId: string | undefined;
  try {
    for (const role of ['admin', 'editor', 'viewer'] as const) ids.push((await prisma.user.create({ data: { email: `${token}-${role}@example.invalid`, role } })).id);
    organizationId = (await prisma.organization.create({ data: { name: token } })).id;
    for (const userId of ids) await prisma.organizationMember.create({ data: { organizationId, userId } });
    await changeDocumentationGrant(ids[0], organizationId, ids[1], 'administrator');
    await changeDocumentationGrant(ids[0], organizationId, ids[0], 'administrator');
    const document = await prisma.document.create({ data: { userId: ids[1], title: 'Private request document', content: 'EXACT PRIVATE BODY' } });
    documentId = document.id;
    const preview = await previewDocumentOwnership(ids[1], document.id, organizationId, document.updatedAt.toISOString());
    const input = { key: randomUUID(), destinationOrganizationId: organizationId, expectedUpdatedAt: preview.updatedAt, previewFingerprint: preview.fingerprint };
    await expect(prepareDocumentOwnershipRequest(ids[0], document.id, input)).rejects.toMatchObject({ status: 404 });
    await expect(prepareDocumentOwnershipRequest(ids[2], document.id, input)).rejects.toMatchObject({ status: 403 });
    await expect(prepareDocumentOwnershipRequest(ids[1], document.id, { ...input, key: 'invalid' })).rejects.toMatchObject({ status: 400 });
    await expect(prepareDocumentOwnershipRequest(ids[1], document.id, { ...input, previewFingerprint: '0'.repeat(64) })).rejects.toMatchObject({ status: 409 });
    expect(await prisma.documentOwnershipRequest.count({ where: { actorId: ids[1] } })).toBe(0);
    const pair = await Promise.all([prepareDocumentOwnershipRequest(ids[1], document.id, input), prepareDocumentOwnershipRequest(ids[1], document.id, input)]);
    expect(pair[0].request.id).toBe(pair[1].request.id);
    expect(pair.map(result => result.replayed).sort()).toEqual([false, true]);
    const pending = pair[0].request;
    expect(pending).toMatchObject({ status: 'pending', expired: false, consentedAt: null, executionAvailable: false });
    expect(await prisma.document.findUniqueOrThrow({ where: { id: document.id } })).toEqual(document);
    expect(await prisma.activityLog.count({ where: { resourceId: document.id, action: 'document.ownership.request' } })).toBe(1);
    const associated = await prisma.document.create({ data: { userId: ids[0], organizationId, title: 'Preserve association on failed deletion', content: 'EXACT ASSOCIATED BODY', visibility: 'org' } });
    associatedDocumentId = associated.id;
    await expect(deleteOrganization(ids[0], organizationId)).rejects.toMatchObject({ status: 409 });
    expect(await prisma.document.findUniqueOrThrow({ where: { id: associated.id } })).toEqual(associated);
    expect(await prisma.organization.findUnique({ where: { id: organizationId } })).not.toBeNull();
    await expect(prepareDocumentOwnershipRequest(ids[1], document.id, { ...input, previewFingerprint: '1'.repeat(64) })).rejects.toMatchObject({ status: 409 });
    const stored = await prisma.documentOwnershipRequest.findUniqueOrThrow({ where: { id: pending.id } });
    await expect(prisma.documentOwnershipRequest.create({ data: { ...stored, id: randomUUID() } })).rejects.toMatchObject({ code: 'P2002' });
    await expect(prisma.documentOwnershipRequest.update({ where: { id: pending.id }, data: { previewFingerprint: '2'.repeat(64) } })).rejects.toThrow();
    await expect(prisma.documentOwnershipRequest.update({ where: { id: pending.id }, data: { status: 'completed' } })).rejects.toThrow();
    expect((await readDocumentOwnershipRequest(ids[1], pending.id)).status).toBe('pending');
    await expect(readDocumentOwnershipRequest(ids[0], pending.id)).rejects.toMatchObject({ status: 404 });
    await expect(cancelDocumentOwnershipRequest(ids[0], pending.id)).rejects.toMatchObject({ status: 404 });
    const child = spawnSync(process.execPath, ['-e', 'const {PrismaClient}=require("@prisma/client");const db=new PrismaClient();db.documentOwnershipRequest.findUniqueOrThrow({where:{id:process.argv[1]}}).then(r=>process.stdout.write(JSON.stringify({id:r.id,status:r.status}))).finally(()=>db.$disconnect());', pending.id], { cwd: process.cwd(), encoding: 'utf8' });
    expect(child.status, child.stderr).toBe(0);
    expect(JSON.parse(child.stdout)).toEqual({ id: pending.id, status: 'pending' });
    await prisma.$disconnect();
    expect((await prepareDocumentOwnershipRequest(ids[1], document.id, input)).request.id).toBe(pending.id);
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(new Date(pending.expiresAt).getTime() + 1));
    expect((await readDocumentOwnershipRequest(ids[1], pending.id)).expired).toBe(true);
    expect((await prepareDocumentOwnershipRequest(ids[1], document.id, input)).request.expired).toBe(true);
    vi.useRealTimers();
    await changeDocumentationGrant(ids[0], organizationId, ids[1], 'reader');
    expect((await prepareDocumentOwnershipRequest(ids[1], document.id, input)).replayed).toBe(true);
    await expect(prepareDocumentOwnershipRequest(ids[1], document.id, { ...input, key: randomUUID() })).rejects.toMatchObject({ status: 404 });
    await prisma.user.update({ where: { id: ids[1] }, data: { role: 'viewer' } });
    const cancelled = await Promise.all([cancelDocumentOwnershipRequest(ids[1], pending.id), cancelDocumentOwnershipRequest(ids[1], pending.id)]);
    expect(cancelled.map(result => result.status)).toEqual(['cancelled', 'cancelled']);
    expect(await prisma.activityLog.count({ where: { resourceId: document.id, action: 'document.ownership.cancel' } })).toBe(1);
    await expect(prepareDocumentOwnershipRequest(ids[1], document.id, input)).rejects.toMatchObject({ status: 403 });
    await expect(prisma.documentOwnershipRequest.update({ where: { id: pending.id }, data: { status: 'pending', cancelledAt: null } })).rejects.toThrow();
    await prisma.document.delete({ where: { id: document.id } });
    documentId = undefined;
    expect(await readDocumentOwnershipRequest(ids[1], pending.id)).toMatchObject({ documentId: document.id, documentAvailable: false, status: 'cancelled' });
    await prisma.user.update({ where: { id: ids[1] }, data: { role: 'editor' } });
    expect((await prepareDocumentOwnershipRequest(ids[1], document.id, input)).request).toMatchObject({ documentAvailable: false, status: 'cancelled' });
    await expect(deleteOrganization(ids[1], organizationId)).rejects.toMatchObject({ status: 403 });
    await expect(deleteOrganization(ids[0], organizationId)).rejects.toMatchObject({ status: 409 });
    await prisma.documentOwnershipRequest.deleteMany({ where: { actorId: ids[1] } });
    await deleteOrganization(ids[0], organizationId);
    organizationId = undefined;
    expect(await prisma.document.findUniqueOrThrow({ where: { id: associated.id } })).toMatchObject({ organizationId: null, visibility: 'private', content: associated.content });
  } finally {
    vi.useRealTimers();
    await prisma.documentOwnershipRequest.deleteMany({ where: { actorId: { in: ids } } });
    if (documentId) await prisma.document.deleteMany({ where: { id: documentId } });
    if (associatedDocumentId) await prisma.document.deleteMany({ where: { id: associatedDocumentId } });
    await prisma.activityLog.deleteMany({ where: { userId: { in: ids } } });
    if (organizationId) await prisma.organization.delete({ where: { id: organizationId } });
    await prisma.user.deleteMany({ where: { id: { in: ids } } });
    await prisma.$disconnect();
  }
}, 30_000);
