#!/usr/bin/env bash
#
# FlexDocs first-time setup — checks prerequisites, generates secrets,
# and starts the stack. Safe to re-run: an existing .env is never overwritten.
#
# Usage:
#   bash scripts/setup.sh              # full setup + start
#   bash scripts/setup.sh --env-only   # generate .env only, don't start
#
set -euo pipefail

cd "$(dirname "$0")/.."

PORT="${PORT:-3001}"

ENV_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --env-only) ENV_ONLY=1 ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

say()  { printf '\n\033[1m== %s\033[0m\n' "$1"; }
fail() { printf '\n\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

# --- 1. Prerequisites -------------------------------------------------------
say "Checking prerequisites"

command -v docker >/dev/null 2>&1 || fail "Docker is not installed.
  macOS:   brew install --cask docker   (then start Docker Desktop)
  Linux:   curl -fsSL https://get.docker.com | sh
  Windows: install Docker Desktop + WSL2, run from WSL"

if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  fail "Docker Compose not found. Update Docker, or install the compose plugin."
fi

docker info >/dev/null 2>&1 || fail "Docker daemon is not running.
  Start Docker Desktop (macOS/Windows) or run: sudo systemctl start docker"

command -v openssl >/dev/null 2>&1 || fail "openssl is required for secret generation."

echo "docker: OK ($DC)"

# --- 2. Environment ---------------------------------------------------------
say "Environment"

if [ -f .env ]; then
  echo ".env already exists — keeping your configuration."
else
  ENCRYPTION_KEY=$(openssl rand -hex 32)
  NEXTAUTH_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 12)

  cat > .env <<EOF
# Generated by scripts/setup.sh — $(date +%F)
# Keep this file private. Never commit it.

DATABASE_URL="postgresql://flexdocs:${DB_PASSWORD}@db:5432/flexdocs"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
NEXTAUTH_URL="http://localhost:${PORT}"
ENCRYPTION_KEY="${ENCRYPTION_KEY}"
DB_PASSWORD="${DB_PASSWORD}"

REDIS_URL="redis://redis:6379"

# Email alerts (optional — leave empty to disable)
SMTP_HOST=""
SMTP_PORT=587
SMTP_USER=""
SMTP_PASS=""
SMTP_FROM="FlexDocs <noreply@flexdocs.local>"
SMTP_SECURE=false

LOG_LEVEL="info"
BACKUP_DIR="./backups"
BACKUP_RETENTION_DAYS=30
EOF
  echo "Created .env with fresh secrets (ENCRYPTION_KEY, NEXTAUTH_SECRET, DB_PASSWORD)."
fi

if [ "$ENV_ONLY" = "1" ]; then
  say "Done (.env only — start later with: $DC up -d --build)"
  exit 0
fi

# --- 3. Build & start --------------------------------------------------------
say "Building and starting (first build takes a few minutes)"

$DC up -d --build

# --- 4. Wait for health ------------------------------------------------------
say "Waiting for the app to become healthy"

for i in $(seq 1 60); do
  if curl -fsS "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
    echo "App is healthy."
    break
  fi
  [ "$i" = "60" ] && fail "App did not become healthy in time. Check: $DC logs app"
  sleep 3
done

# --- 5. Done ------------------------------------------------------------------
say "FlexDocs is running"

cat <<'EOF'

  URL:      http://localhost:${PORT}
  Login:    admin@flexdocs.local
  Password: admin12345

  !! Change this password right away (Profile → Change Password) —
  !! it is public in the source code.

  Useful commands:
    docker compose logs -f app     # app logs
    docker compose down            # stop (data is kept in volumes)
    bash scripts/backup.sh         # database backup

EOF
